/*
 * Copyright (C) 2012 Freescale Semiconductor, Inc. All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _BOARD_MX6DL_QPAD_H
#define _BOARD_MX6DL_QPAD_H
#include <mach/iomux-mx6dl.h>

#define MX6DL_KEYPAD_PAD_CTRL	(PAD_CTL_PKE | PAD_CTL_PUE |	\
		PAD_CTL_PUS_22K_UP | PAD_CTL_SPEED_MED|	\
		PAD_CTL_DSE_40ohm | PAD_CTL_HYS)

#define MX6DL_GENERIC_PAD_CTRL	(PAD_CTL_PKE | PAD_CTL_PUE |	\
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED|	\
		PAD_CTL_DSE_40ohm | PAD_CTL_HYS)

#define MX6DL_WLAN_PAD_CTRL	(PAD_CTL_PKE | PAD_CTL_PUE |	\
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED|	\
		PAD_CTL_DSE_40ohm | PAD_CTL_HYS)

static iomux_v3_cfg_t mx6dl_qpad_pads[] = {
	/* AUDMUX */
	MX6DL_PAD_CSI0_DAT4__AUDMUX_AUD3_TXC,
	MX6DL_PAD_CSI0_DAT5__AUDMUX_AUD3_TXD,
	MX6DL_PAD_CSI0_DAT6__AUDMUX_AUD3_TXFS,
	MX6DL_PAD_CSI0_DAT7__AUDMUX_AUD3_RXD,


	/* CCM  */
	MX6DL_PAD_GPIO_0__CCM_CLKO,		/* Clock output 1: Camera MCLK */
	MX6DL_PAD_NANDF_CS2__CCM_CLKO2,	/* Clock output 2: Audio Codec MCLK*/
	MX6DL_PAD_GPIO_8__ANATOP_ANATOP_32K_OUT,/*32K Reference clock output*/


	/* PMIC */
	MX6DL_PAD_GPIO_18__GPIO_7_13,	/*PMIC INT*/
	MX6DL_PAD_GPIO_9__WDOG1_WDOG_B,	/*Watchdog output to reset system*/

	/* SW4 , SW5 & SW1 */
	MX6DL_PAD_NANDF_WP_B__GPIO_6_9,	/* FUN1,QR_SCAN_EN1*/
	MX6DL_PAD_NANDF_RB0__GPIO_6_10,	/* FUN2,QR_SCAN_EN2*/
	MX6DL_PAD_EIM_D29__GPIO_3_29,		/* PWR BUTTON*/


	/* I2C1 */
	MX6DL_PAD_CSI0_DAT8__I2C1_SDA,
	MX6DL_PAD_CSI0_DAT9__I2C1_SCL,

	/* I2C2 */
	MX6DL_PAD_KEY_COL3__I2C2_SCL,
	MX6DL_PAD_KEY_ROW3__I2C2_SDA,

	/* I2C3 */
	MX6DL_PAD_GPIO_3__I2C3_SCL,
	MX6DL_PAD_GPIO_6__I2C3_SDA,

	/* DISPLAY ,MIPI is proprietary PINs*/
	NEW_PAD_CTRL(MX6DL_PAD_NANDF_D6__GPIO_2_6,MX6DL_GENERIC_PAD_CTRL),	/*LCD_PWR*/
	NEW_PAD_CTRL(MX6DL_PAD_KEY_ROW4__GPIO_4_15,MX6DL_GENERIC_PAD_CTRL),	/*LCD_PWR_EN,backlight enable*/
	NEW_PAD_CTRL(MX6DL_PAD_NANDF_CS3__GPIO_6_16,MX6DL_GENERIC_PAD_CTRL),/*LCD_RST_B*/
	
	/* PWM */
	MX6DL_PAD_SD1_DAT3__PWM1_PWMO,		/* LCD_PWM*/
	MX6DL_PAD_DISP0_DAT9__PWM2_PWMO,	/* Infrared Modulation PWM*/

	/* UART */
	MX6DL_PAD_CSI0_DAT10__UART1_TXD,
	MX6DL_PAD_CSI0_DAT11__UART1_RXD,
	MX6DL_PAD_EIM_D26__UART2_TXD,
	MX6DL_PAD_EIM_D27__UART2_RXD,
	MX6DL_PAD_EIM_D24__UART3_TXD,
	MX6DL_PAD_EIM_D25__UART3_RXD,
	MX6DL_PAD_KEY_COL0__UART4_TXD,
	MX6DL_PAD_KEY_ROW0__UART4_RXD,
	MX6DL_PAD_KEY_COL1__UART5_TXD,
	MX6DL_PAD_KEY_ROW1__UART5_RXD,

	/* USB OTG */
	MX6DL_PAD_GPIO_1__USBOTG_ID,
	MX6DL_PAD_EIM_D22__GPIO_3_22,

	/* USDHC2 */
	MX6DL_PAD_SD2_CLK__USDHC2_CLK,
	MX6DL_PAD_SD2_CMD__USDHC2_CMD,
	MX6DL_PAD_SD2_DAT0__USDHC2_DAT0,
	MX6DL_PAD_SD2_DAT1__USDHC2_DAT1,
	MX6DL_PAD_SD2_DAT2__USDHC2_DAT2,
	MX6DL_PAD_SD2_DAT3__USDHC2_DAT3,
	MX6DL_PAD_NANDF_D0__GPIO_2_0,

	/* USDHC3 4bit*/
	MX6DL_PAD_SD3_CLK__USDHC3_CLK_50MHZ,
	MX6DL_PAD_SD3_CMD__USDHC3_CMD_50MHZ,
	MX6DL_PAD_SD3_DAT0__USDHC3_DAT0_50MHZ,
	MX6DL_PAD_SD3_DAT1__USDHC3_DAT1_50MHZ,
	MX6DL_PAD_SD3_DAT2__USDHC3_DAT2_50MHZ,
	MX6DL_PAD_SD3_DAT3__USDHC3_DAT3_50MHZ,
	MX6DL_PAD_SD3_DAT4__GPIO_7_1,//w_dev
	MX6DL_PAD_SD3_DAT6__GPIO_6_18,//w_host
	
	/* USDHC4 8bit*/
	MX6DL_PAD_SD4_CLK__USDHC4_CLK_50MHZ,
	MX6DL_PAD_SD4_CMD__USDHC4_CMD_50MHZ,
	MX6DL_PAD_SD4_DAT0__USDHC4_DAT0_50MHZ,
	MX6DL_PAD_SD4_DAT1__USDHC4_DAT1_50MHZ,
	MX6DL_PAD_SD4_DAT2__USDHC4_DAT2_50MHZ,
	MX6DL_PAD_SD4_DAT3__USDHC4_DAT3_50MHZ,
	MX6DL_PAD_SD4_DAT4__USDHC4_DAT4_50MHZ,
	MX6DL_PAD_SD4_DAT5__USDHC4_DAT5_50MHZ,
	MX6DL_PAD_SD4_DAT6__USDHC4_DAT6_50MHZ,
	MX6DL_PAD_SD4_DAT7__USDHC4_DAT7_50MHZ,

	/* Charger&Battery */
	MX6DL_PAD_EIM_A25__GPIO_5_2,  /* CHG_FLT1_B */
	NEW_PAD_CTRL(MX6DL_PAD_EIM_D23__GPIO_3_23,PAD_CTL_PUE|PAD_CTL_HYS), /* CHG_STATUS1_B */
	MX6DL_PAD_EIM_D17__GPIO_3_17,  /* UOK_B */
	MX6DL_PAD_EIM_CS1__GPIO_2_24,   /* DOK_B */
	MX6DL_PAD_KEY_COL4__GPIO_4_14,	/*Battery Alert IRQ*/
	NEW_PAD_CTRL(MX6DL_PAD_KEY_ROW2__GPIO_4_11,PAD_CTL_DSE_DISABLE),	/*Batter Detection*/

	/* Audio Codec */
	MX6DL_PAD_EIM_D21__GPIO_3_21,		/* MICROPHONE_DET */
	MX6DL_PAD_GPIO_16__GPIO_7_11,		/*AUDIO_RST_N*/
	MX6DL_PAD_SD1_CLK__GPIO_1_20,		/*AUDIO_INT*/
	
	/*Hardware Monitor*/
	MX6DL_PAD_EIM_CS0__GPIO_2_23,		/*SENSOR_RST*/

	/*QR Engine*/
	NEW_PAD_CTRL(MX6DL_PAD_EIM_D30__GPIO_3_30,MX6DL_GENERIC_PAD_CTRL),		/*QR_TRIG*/
	NEW_PAD_CTRL(MX6DL_PAD_EIM_BCLK__GPIO_6_31,MX6DL_GENERIC_PAD_CTRL),		/*MX6DL_PAD_EIM_DA8__GPIO_3_8,	change to BCLK because of confliction of BOOT_CFG*/		/*QR_RESET*/

	/*Touch Panel*/
	MX6DL_PAD_EIM_EB0__GPIO_2_28,		/*TP_PWR_EN*/
	MX6DL_PAD_NANDF_ALE__GPIO_6_8,		/*TP_RST*/
	MX6DL_PAD_NANDF_CLE__GPIO_6_7,		/*TP_IRQ*/

	/*GPS*/
	MX6DL_PAD_EIM_D18__GPIO_3_18,		/*GPS_PPS*/
	MX6DL_PAD_EIM_DA0__GPIO_3_0,			/*GPS_PWR_EN*/

	/*FlashLight*/
	MX6DL_PAD_EIM_D31__GPIO_3_31,		/*FL_PWR_EN*/
	MX6DL_PAD_GPIO_19__GPIO_4_5,			/*FLASHLIGHT_EN*/
	
	/*W1*/
	NEW_PAD_CTRL(MX6DL_PAD_EIM_D28__GPIO_3_28,NO_PAD_CTRL),		/*OneWire*/

	/*WiFi*/
	NEW_PAD_CTRL(MX6DL_PAD_SD3_RST__GPIO_7_8,MX6DL_WLAN_PAD_CTRL),			/*WiFi Reset*/
	NEW_PAD_CTRL(MX6DL_PAD_NANDF_CS0__GPIO_6_11,MX6DL_WLAN_PAD_CTRL),		/*WiFi PowerDown*/
	
	/*Modem*/
	MX6DL_PAD_NANDF_D2__GPIO_2_2,		/*3G_DIS_N :OnOff*/
	MX6DL_PAD_NANDF_D3__GPIO_2_3,		/*3G_PRST_N: Reset*/
	MX6DL_PAD_NANDF_D4__GPIO_2_4,		/*3G_PWR*/
	MX6DL_PAD_NANDF_D5__GPIO_2_5,		/*3GWakeModem*/
	MX6DL_PAD_SD1_CMD__GPIO_1_18,		/*3GWakeAP*/
};

static iomux_v3_cfg_t mx6dl_qpad_barcode_pads_v2[] = {
	MX6DL_PAD_EIM_D30__GPIO_3_30,	/*QR Trig*/
	MX6DL_PAD_EIM_BCLK__GPIO_6_31,	/*QR Wake*/
	MX6DL_PAD_EIM_OE__GPIO_2_25,		/*QR_PWN*/
	MX6DL_PAD_GPIO_7__GPIO_1_7,		/*QR_PWR_EN*/
};

static iomux_v3_cfg_t mx6dl_qpad_hp_uart_switcher_pads_v2[] = {
	MX6DL_PAD_EIM_D19__GPIO_3_19,	/*SELECT_IN2*/
	MX6DL_PAD_NANDF_CS1__GPIO_6_14,	/*SELECT_IN1*/	
};






static iomux_v3_cfg_t mx6dl_qpad_csi0_sensor_pads[] = {
	/* IPU1 Camera */
	MX6DL_PAD_CSI0_DAT12__IPU1_CSI0_D_12,
	MX6DL_PAD_CSI0_DAT13__IPU1_CSI0_D_13,
	MX6DL_PAD_CSI0_DAT14__IPU1_CSI0_D_14,
	MX6DL_PAD_CSI0_DAT15__IPU1_CSI0_D_15,
	MX6DL_PAD_CSI0_DAT16__IPU1_CSI0_D_16,
	MX6DL_PAD_CSI0_DAT17__IPU1_CSI0_D_17,
	MX6DL_PAD_CSI0_DAT18__IPU1_CSI0_D_18,
	MX6DL_PAD_CSI0_DAT19__IPU1_CSI0_D_19,

	/*data enable available ??? */
	//MX6DL_PAD_CSI0_DATA_EN__IPU1_CSI0_DATA_EN,
	
	MX6DL_PAD_CSI0_MCLK__IPU1_CSI0_HSYNC,
	MX6DL_PAD_CSI0_PIXCLK__IPU1_CSI0_PIXCLK,
	MX6DL_PAD_CSI0_VSYNC__IPU1_CSI0_VSYNC,

	MX6DL_PAD_GPIO_0__CCM_CLKO,		/* camera clk */

	MX6DL_PAD_SD1_DAT0__GPIO_1_16,		/* camera PWDN */
	
	MX6DL_PAD_CSI0_DATA_EN__GPIO_5_20,	/* camera RESET */

};



#endif
